#!/bin/bash

if [ -n "$1" ] 
then
n=$1
else
n=01
fi

echo 
echo "****************************************************************"
echo "Creating test image $n."
echo "For other tables, see samples/parse-table-X.conf and then use"
echo ""
echo "> makeimage X"
echo ""
echo "e.g. makeimage 02a"
echo "****************************************************************"
echo 
echo

echo "Parsing table and creating conf/data files in data/"
cat samples/table-$n.txt | bin/parse-table -conf samples/parse-table-$n.conf | bin/make-conf -dir data
echo "Drawing Circos image using etc/circos.conf and parsed files from data/"
../../bin/circos -conf etc/circos.conf -outputfile table-$n.png | grep created


