#!/bin/bash

echo "Creating image circos.png and writing report to run.out."

echo "Example takes ~45-60 seconds to generate."

../bin/circos -conf etc/circos.conf -debug_group summary,timer > run.out

